export const data = {
  labels: [
    ["Creativity", "HTML", "SpringBoot"],
    ["Comunication", "CSS", "PHP"],
    ["Poblem Solving", "JavaScript", "Django"],
    ["Team Work", "Bootstrap", "MySQL"],
    ["Curiosity", "React", "NodeJS"],
    ["Ants", "Figma", "Git"],
  ],
  datasets: [
    {
      label: "Personal Skills",
      data: [70, 75, 50, 80, 100, 90],
      fill: true,
      backgroundColor: "rgba(54, 162, 235, 0.2)",
      borderColor: "rgb(54, 162, 235)",
      pointBackgroundColor: "rgb(54, 162, 235)",
      pointBorderColor: "#fff",
      pointHoverBackgroundColor: "#fff",
      pointHoverBorderColor: "rgb(54, 162, 235)",
    },
    {
      label: "FRONTEND",
      data: [90, 70, 70, 60, 30, 20],
      fill: true,
      backgroundColor: "rgba(99,75,138,0.2)",
      borderColor: "rgb(99, 75, 138)",
      pointBackgroundColor: "rgb(99, 75, 138)",
      pointBorderColor: "#fff",
      pointHoverBackgroundColor: "#fff",
      pointHoverBorderColor: "rgb(99, 75, 138)",
    },
    {
      label: "BACKEND",
      data: [50, 20, 40, 50, 60, 30],
      fill: true,
      backgroundColor: "rgba(221,120,12,0.2)",
      borderColor: "rgb(221,120,12)",
      pointBackgroundColor: "rgb(221, 120, 12)",
      pointBorderColor: "#fff",
      pointHoverBackgroundColor: "#fff",
      pointHoverBorderColor: "rgb(221,120, 12)",
    },
  ],
};
